project:
  name: SOLID Principles
  author: Sajid

data:
  root_dir: ./data
  raw_dir: ./data/raw/
  processed_dir: ./data/processed/
  train_split: 0.8
  image_size: [224, 224]

features:
  method: S
  n_features: 500

